Experiment Tracker

In [1]:
# ==========================================
# Imports
# ==========================================

import pandas as pd
from pathlib import Path

Experiment History

In [2]:
# ==========================================
# Initialize Experiment Tracker
# ==========================================

experiment_tracker = pd.DataFrame({
    "Experiment ID": [],
    "Model": [],
    "Accuracy": [],
    "Precision (Macro)": [],
    "Recall (Macro)": [],
    "F1 Score (Macro)": [],
    "Training Time (min)": [],
    "Status": [],
    "Remarks": []
})

experiment_tracker

Empty DataFrame
Columns: [Experiment ID, Model, Accuracy, Precision (Macro), Recall (Macro), F1 Score (Macro), Training Time (min), Status, Remarks]
Index: []

Add Existing Experiments

In [3]:
# ==========================================
# Add Completed Experiments
# ==========================================

experiment_tracker = pd.DataFrame([
    {
        "Experiment ID": "E01",
        "Model": "Baseline Random Forest",
        "Accuracy": 0.5964,
        "Precision (Macro)": 0.50,
        "Recall (Macro)": 0.43,
        "F1 Score (Macro)": 0.43,
        "Training Time (min)": 27.38,
        "Status": "Baseline",
        "Remarks": "Initial production baseline."
    },
    {
        "Experiment ID": "E02",
        "Model": "Balanced Random Forest",
        "Accuracy": 0.5542,
        "Precision (Macro)": 0.47,
        "Recall (Macro)": 0.47,
        "F1 Score (Macro)": 0.45,
        "Training Time (min)": 27.84,
        "Status": "Rejected",
        "Remarks": "Improved minority recall but lower overall accuracy."
    },
    {
        "Experiment ID": "E03",
        "Model": "Tuned Random Forest",
        "Accuracy": 0.6129,
        "Precision (Macro)": 0.60,
        "Recall (Macro)": 0.39,
        "F1 Score (Macro)": 0.37,
        "Training Time (min)": 3.30,
        "Status": "Candidate",
        "Remarks": "Highest accuracy, but weaker recall for High and Medium risk."
    }
])

experiment_tracker

,Experiment ID,Model,Accuracy,Precision (Macro),Recall (Macro),F1 Score (Macro),Training Time (min),Status,Remarks
0,E01,Baseline Random Forest,0.5964,0.50,0.43,0.43,27.38,Baseline,Initial production baseline.
1,E02,Balanced Random Forest,0.5542,0.47,0.47,0.45,27.84,Rejected,Improved minority recall but lower overall acc...
2,E03,Tuned Random Forest,0.6129,0.60,0.39,0.37,3.30,Candidate,"Highest accuracy, but weaker recall for High a..."

Save Experiment Tracker

In [4]:
# ==========================================
# Save Experiment Tracker
# ==========================================

from pathlib import Path

REPORTS_DIR = Path("../reports")
REPORTS_DIR.mkdir(exist_ok=True)

tracker_path = REPORTS_DIR / "experiment_tracker.csv"

experiment_tracker.to_csv(
    tracker_path,
    index=False
)

print("Experiment tracker saved successfully!")
print(f"Location: {tracker_path.resolve()}")

Experiment tracker saved successfully!
Location: D:\SOUMIT MANNA\IEM\Internship\Summer Internship\SafeStreet\ml_backend\reports\experiment_tracker.csv

In [1]:
# ==========================================
# Load Experiment Tracker
# ==========================================

import pandas as pd
from pathlib import Path

tracker_path = Path("../reports/experiment_tracker.csv")

experiment_tracker = pd.read_csv(tracker_path)

print("Experiment Tracker Loaded Successfully!")
print()

experiment_tracker

Experiment Tracker Loaded Successfully!

,Experiment ID,Model,Accuracy,Precision (Macro),Recall (Macro),F1 Score (Macro),Training Time (min),Status,Remarks
0,E01,Baseline Random Forest,0.5964,0.50,0.43,0.43,27.38,Baseline,Initial production baseline.
1,E02,Balanced Random Forest,0.5542,0.47,0.47,0.45,27.84,Rejected,Improved minority recall but lower overall acc...
2,E03,Tuned Random Forest,0.6129,0.60,0.39,0.37,3.30,Candidate,"Highest accuracy, but weaker recall for High a..."

In [2]:
# ==========================================
# Add Experiment E04 - XGBoost
# ==========================================

new_experiment = pd.DataFrame([
    {
        "Experiment ID": "E04",
        "Model": "XGBoost",
        "Accuracy": 0.6227,
        "Precision (Macro)": 0.59,
        "Recall (Macro)": 0.43,
        "F1 Score (Macro)": 0.43,
        "Training Time (min)": 0.32,
        "Status": "Candidate",
        "Remarks": "Best accuracy so far with extremely fast training."
    }
])

experiment_tracker = pd.concat(
    [experiment_tracker, new_experiment],
    ignore_index=True
)

experiment_tracker

,Experiment ID,Model,Accuracy,Precision (Macro),Recall (Macro),F1 Score (Macro),Training Time (min),Status,Remarks
0,E01,Baseline Random Forest,0.5964,0.50,0.43,0.43,27.38,Baseline,Initial production baseline.
1,E02,Balanced Random Forest,0.5542,0.47,0.47,0.45,27.84,Rejected,Improved minority recall but lower overall acc...
2,E03,Tuned Random Forest,0.6129,0.60,0.39,0.37,3.30,Candidate,"Highest accuracy, but weaker recall for High a..."
3,E04,XGBoost,0.6227,0.59,0.43,0.43,0.32,Candidate,Best accuracy so far with extremely fast train...

In [3]:
# ==========================================
# Save Updated Experiment Tracker
# ==========================================

experiment_tracker.to_csv(
    tracker_path,
    index=False
)

print("Experiment Tracker Updated Successfully!")
print(f"Saved at: {tracker_path.resolve()}")

Experiment Tracker Updated Successfully!
Saved at: D:\SOUMIT MANNA\IEM\Internship\Summer Internship\SafeStreet\ml_backend\reports\experiment_tracker.csv

In [4]:
# ==========================================
# Add Experiment E05 - CatBoost
# ==========================================

new_experiment = pd.DataFrame([
    {
        "Experiment ID": "E05",
        "Model": "CatBoost",
        "Accuracy": 0.6201,
        "Precision (Macro)": 0.59,
        "Recall (Macro)": 0.42,
        "F1 Score (Macro)": 0.42,
        "Training Time (min)": 0.66,
        "Status": "Candidate",
        "Remarks": "Very close to XGBoost but slightly lower accuracy and slower training."
    }
])

experiment_tracker = pd.concat(
    [experiment_tracker, new_experiment],
    ignore_index=True
)

experiment_tracker

,Experiment ID,Model,Accuracy,Precision (Macro),Recall (Macro),F1 Score (Macro),Training Time (min),Status,Remarks
0,E01,Baseline Random Forest,0.5964,0.50,0.43,0.43,27.38,Baseline,Initial production baseline.
1,E02,Balanced Random Forest,0.5542,0.47,0.47,0.45,27.84,Rejected,Improved minority recall but lower overall acc...
2,E03,Tuned Random Forest,0.6129,0.60,0.39,0.37,3.30,Candidate,"Highest accuracy, but weaker recall for High a..."
3,E04,XGBoost,0.6227,0.59,0.43,0.43,0.32,Candidate,Best accuracy so far with extremely fast train...
4,E05,CatBoost,0.6201,0.59,0.42,0.42,0.66,Candidate,Very close to XGBoost but slightly lower accur...

In [6]:
# ==========================================
# Select Current Champion Model
# ==========================================

# Reset all candidate models
experiment_tracker.loc[
    experiment_tracker["Status"] == "Champion",
    "Status"
] = "Candidate"

# Set XGBoost as the current champion
experiment_tracker.loc[
    experiment_tracker["Model"] == "XGBoost",
    "Status"
] = "Champion"

experiment_tracker[
    ["Experiment ID", "Model", "Accuracy", "Status"]
]

  Experiment ID                   Model  Accuracy     Status
0           E01  Baseline Random Forest    0.5964   Baseline
1           E02  Balanced Random Forest    0.5542   Rejected
2           E03     Tuned Random Forest    0.6129  Candidate
3           E04                 XGBoost    0.6227   Champion
4           E05                CatBoost    0.6201  Candidate

In [7]:
# ==========================================
# Save Final Experiment Tracker
# ==========================================

experiment_tracker.to_csv(
    tracker_path,
    index=False
)

print("Experiment Tracker Saved Successfully!")
print(f"Saved to: {tracker_path.resolve()}")

Experiment Tracker Saved Successfully!
Saved to: D:\SOUMIT MANNA\IEM\Internship\Summer Internship\SafeStreet\ml_backend\reports\experiment_tracker.csv